import { 
  User, Department, ComplaintCategory, Complaint, IncidentCluster, 
  NotificationItem, AuditLog, SystemStats 
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-citizen-1',
    name: 'Ramesh Reddy',
    phone: '+91 98765 43210',
    email: 'ramesh.reddy@citizens.gov.in',
    role: 'citizen',
    language: 'te',
    state: 'Telangana',
    district: 'Rangareddy',
    local_body: 'GHMC Ward 12 (Serilingampally)',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-officer-1',
    name: 'K. Suresh Kumar',
    phone: '+91 94401 22334',
    email: 'suresh.k@roads.telangana.gov.in',
    employeeId: 'ENG-RND-4402',
    role: 'field_officer',
    department_id: 'dept-roads',
    language: 'en',
    state: 'Telangana',
    district: 'Rangareddy',
    local_body: 'GHMC Ward 12 & 13',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-panchayat-1',
    name: 'M. Lakshmi Devi',
    phone: '+91 98480 11223',
    email: 'lakshmi.devi@panchayat.gov.in',
    employeeId: 'PANCH-SR-091',
    role: 'panchayat_staff',
    department_id: 'dept-sanitation',
    language: 'te',
    state: 'Telangana',
    district: 'Rangareddy',
    local_body: 'Gachibowli Local Body Office',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-dept-1',
    name: 'P. Venkat Rao',
    phone: '+91 98490 55667',
    email: 'venkat.rao@telangana.gov.in',
    employeeId: 'EE-RBD-8810',
    role: 'department_officer',
    department_id: 'dept-roads',
    language: 'en',
    state: 'Telangana',
    district: 'Rangareddy',
    local_body: 'Circle 11 Headquarters',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-district-1',
    name: 'Dr. Ananya Sharma, IAS',
    phone: '+91 91210 99887',
    email: 'collector.rangareddy@telangana.gov.in',
    employeeId: 'IAS-TG-2016-042',
    role: 'district_admin',
    language: 'en',
    state: 'Telangana',
    district: 'Rangareddy',
    local_body: 'District Collectorate Office',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-admin-1',
    name: 'Rajesh Varma',
    phone: '+91 99000 11122',
    email: 'admin.prajavaani@telangana.gov.in',
    employeeId: 'IT-CIVIC-001',
    role: 'super_admin',
    language: 'en',
    state: 'Telangana',
    district: 'Statewide',
    local_body: 'Civic Intelligence Command Center',
    created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-roads',
    name: 'Roads & Buildings Department',
    code: 'R&B-DIV',
    description: 'Maintenance of arterial roads, pothole repairs, street pavement and bridges.',
    service_area: 'Circle 11, Ward 12, Gachibowli, Madhapur, Serilingampally',
    contact_information: 'tollfree: 1800-425-7623 | roads-help@telangana.gov.in',
    active: true,
    icon: 'construction',
    sla_hours_critical: 4,
    sla_hours_high: 24,
    sla_hours_medium: 72,
    sla_hours_low: 168,
  },
  {
    id: 'dept-sanitation',
    name: 'Sanitation & Solid Waste Management',
    code: 'SWM-DIV',
    description: 'Door-to-door garbage collection, street sweeping, dump yards, and sanitation drive.',
    service_area: 'All Municipal Wards & Gram Panchayats',
    contact_information: 'tollfree: 1800-425-4272 | sanitation@telangana.gov.in',
    active: true,
    icon: 'trash-2',
    sla_hours_critical: 4,
    sla_hours_high: 24,
    sla_hours_medium: 48,
    sla_hours_low: 120,
  },
  {
    id: 'dept-drainage',
    name: 'Drainage & Stormwater Department',
    code: 'DSD-DIV',
    description: 'Underground sewerage, stormwater desiltation, open drains, and anti-inundation works.',
    service_area: 'Zone 3 Low-lying Catchment Zones',
    contact_information: 'phone: 040-23451122 | drainage-control@telangana.gov.in',
    active: true,
    icon: 'waves',
    sla_hours_critical: 3,
    sla_hours_high: 18,
    sla_hours_medium: 72,
    sla_hours_low: 144,
  },
  {
    id: 'dept-water',
    name: 'Municipal Water Supply & Sewerage Board',
    code: 'HMWSSB',
    description: 'Drinking water distribution, pipeline leak repairs, booster pumps and water tankers.',
    service_area: 'Greater Hyderabad & Peri-urban Environs',
    contact_information: 'helpline: 155313 | water-complaints@telangana.gov.in',
    active: true,
    icon: 'droplets',
    sla_hours_critical: 2,
    sla_hours_high: 12,
    sla_hours_medium: 48,
    sla_hours_low: 96,
  },
  {
    id: 'dept-lighting',
    name: 'Public Lighting & Electrical Wing',
    code: 'ELEC-DIV',
    description: 'LED streetlights, high-mast lamps, timers, and overhead power line safety.',
    service_area: 'Rangareddy Urban & Rural Corridors',
    contact_information: 'phone: 040-23348899 | lighting-grievance@telangana.gov.in',
    active: true,
    icon: 'lightbulb',
    sla_hours_critical: 4,
    sla_hours_high: 24,
    sla_hours_medium: 48,
    sla_hours_low: 120,
  },
  {
    id: 'dept-infra',
    name: 'Public Works & Infrastructure Dept',
    code: 'PWD-CIV',
    description: 'Bus shelters, pedestrian footbridges, public school walls, and municipal buildings.',
    service_area: 'District-wide Public Amenities',
    contact_information: 'phone: 040-24750011 | pwd-admin@telangana.gov.in',
    active: true,
    icon: 'building-2',
    sla_hours_critical: 6,
    sla_hours_high: 36,
    sla_hours_medium: 96,
    sla_hours_low: 240,
  },
];

export const INITIAL_CATEGORIES: ComplaintCategory[] = [
  {
    id: 'roads',
    name: 'Road Infrastructure',
    telugu_name: 'రోడ్డు మౌలిక సదుపాయాలు',
    description: 'Potholes, asphalt erosion, open trenches, cracked roads, damaged road dividers.',
    default_department: 'dept-roads',
    default_sla_hours: 24,
    icon: 'truck',
    keywords: ['pothole', 'road', 'asphalt', 'crater', 'divider', 'గుంత', 'రోడ్డు'],
  },
  {
    id: 'sanitation',
    name: 'Sanitation & Solid Waste',
    telugu_name: 'పారిశుధ్యం & చెత్త నిర్వహణ',
    description: 'Uncollected garbage, overflowing community bins, open dumping, animal carcass removal.',
    default_department: 'dept-sanitation',
    default_sla_hours: 24,
    icon: 'trash',
    keywords: ['garbage', 'trash', 'waste', 'dump', 'stench', 'చెత్త'],
  },
  {
    id: 'drainage',
    name: 'Drainage & Stormwater',
    telugu_name: 'కాలువలు & డ్రైనేజీ',
    description: 'Choked manholes, overflowing sewage, culvert siltation, stagnant monsoon water.',
    default_department: 'dept-drainage',
    default_sla_hours: 18,
    icon: 'waves',
    keywords: ['drain', 'sewer', 'sewage', 'manhole', 'overflow', 'కాలువ'],
  },
  {
    id: 'water',
    name: 'Water Supply',
    telugu_name: 'తాగునీటి సరఫరా',
    description: 'Burst pipelines, contaminated tap water, low water pressure, broken valves.',
    default_department: 'dept-water',
    default_sla_hours: 12,
    icon: 'droplet',
    keywords: ['water', 'pipe', 'leak', 'potable', 'supply', 'తాగునీరు'],
  },
  {
    id: 'lighting',
    name: 'Public Lighting',
    telugu_name: 'వీధి దీపాలు',
    description: 'Non-burning streetlights, flickering fixtures, damaged poles, dark roads at night.',
    default_department: 'dept-lighting',
    default_sla_hours: 24,
    icon: 'sun',
    keywords: ['streetlight', 'light', 'dark', 'bulb', 'wire', 'దీపం'],
  },
  {
    id: 'infrastructure',
    name: 'Public Infrastructure',
    telugu_name: 'ప్రజా మౌలిక వసతులు',
    description: 'Damaged footpaths, broken handrails, bus stop shelter collapse, boundary walls.',
    default_department: 'dept-infra',
    default_sla_hours: 48,
    icon: 'wrench',
    keywords: ['footpath', 'shelter', 'wall', 'railing', 'structure'],
  },
];

// Seed Complaints including primary demo PV-2026-004821
export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'comp-4821',
    complaint_number: 'PV-2026-004821',
    citizen_id: 'user-citizen-1',
    citizen_name: 'Ramesh Reddy',
    citizen_phone: '+91 98765 43210',
    title: 'Dangerous Pothole Near School Entrance',
    description: 'There is a large pothole near the school entrance. Two-wheelers are struggling to pass and it becomes dangerous during rain.',
    original_language: 'te',
    original_transcript: 'పాఠశాల దగ్గర పెద్ద గుంత ఉంది, ద్విచక్ర వాహనాలు పడిపోయే ప్రమాదం ఉంది. వర్షంలో నీరు నిలిచిపోయి చాలా ప్రమాదకరంగా మారింది.',
    translated_description: 'There is a large pothole near the school entrance. Two-wheelers are struggling to pass and it becomes dangerous during rain.',
    category_id: 'roads',
    category_name: 'Road Infrastructure',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    latitude: 17.4401,
    longitude: 78.3489,
    address: 'Near Zilla Parishad High School, Main Road, Gachibowli',
    ward: 'Ward 12',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-roads',
    department_name: 'Roads & Buildings Department',
    assigned_officer_id: 'user-officer-1',
    assigned_officer_name: 'K. Suresh Kumar',
    assigned_officer_role: 'Field Officer (Roads)',
    sla_hours_allotted: 24,
    sla_deadline: new Date(Date.now() + 13 * 3600000 + 42 * 60000).toISOString(), // ~13h 42m remaining
    sla_breached: false,
    evidence_quality_score: 84,
    evidence: [
      {
        id: 'evid-1',
        complaint_id: 'comp-4821',
        uploaded_by: 'Ramesh Reddy',
        uploaded_by_role: 'citizen',
        file_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
        file_type: 'image',
        file_name: 'pothole_citizen_evidence.jpg',
        file_size_kb: 420,
        evidence_stage: 'BEFORE',
        ai_analysis: {
          detected_issue: 'Severe road surface asphalt depression / Pothole crater',
          confidence: 0.91,
          clarity_score: 84,
          notes: 'Defect depth ~14cm, high contrast edges, near school boundary.',
        },
        uploaded_at: new Date(Date.now() - 5 * 3600000).toISOString(),
      },
      {
        id: 'evid-2',
        complaint_id: 'comp-4821',
        uploaded_by: 'K. Suresh Kumar',
        uploaded_by_role: 'field_officer',
        file_url: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80',
        file_type: 'image',
        file_name: 'field_inspection_before.jpg',
        file_size_kb: 512,
        evidence_stage: 'PROGRESS',
        ai_analysis: {
          detected_issue: 'Repair crew on site with hot mix asphalt compactor',
          confidence: 0.89,
          clarity_score: 86,
          notes: 'Base excavation complete, sub-base leveling underway.',
        },
        uploaded_at: new Date(Date.now() - 1 * 3600000).toISOString(),
      },
    ],
    ai_analysis: {
      complaint_id: 'comp-4821',
      category: 'Road Infrastructure',
      department: 'Roads & Buildings Department',
      priority: 'HIGH',
      confidence: 0.91,
      summary: {
        issue: 'Severe road pothole crater impeding vehicular flow.',
        location: 'Near Zilla Parishad High School, Main Road, Ward 12.',
        duration: 'Reported active for 3 days.',
        potential_impact: 'Severe safety hazard for two-wheelers and school transport during monsoon rush.',
        recommended_action: 'Patching with bituminous asphalt and mechanical compaction.',
      },
      evidence_score: 84,
      evidence_advice: 'Evidence verified. Pothole dimension and school perimeter clearly visible.',
      explainability: {
        factors: [
          'Safety risk for two-wheelers and pedestrians',
          'Adjacent to school premises (Vulnerable pedestrian zone)',
          'Part of emerging road damage cluster (3 nearby reports)',
          'High waterlogging risk during rainfall',
        ],
        school_or_hospital_proximity: true,
        road_damage_detected: true,
        weather_hazard: true,
        cluster_member: true,
      },
      duplicate_candidates: [
        {
          complaint_id: 'comp-4790',
          complaint_number: 'PV-2026-004790',
          similarity_score: 0.87,
          distance_meters: 80,
          reported_ago: '2 days ago',
        },
      ],
      created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
    history: [
      {
        id: 'hist-1',
        complaint_id: 'comp-4821',
        previous_status: null,
        new_status: 'SUBMITTED',
        changed_by: 'Ramesh Reddy (Citizen)',
        role: 'citizen',
        note: 'Citizen submitted grievance via Mobile Voice Assistant in Telugu.',
        timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
      },
      {
        id: 'hist-2',
        complaint_id: 'comp-4821',
        previous_status: 'SUBMITTED',
        new_status: 'VERIFIED',
        changed_by: 'PRAJAVAANI AI Engine',
        role: 'super_admin',
        note: 'AI classified category: Road Infrastructure (94%), Priority: HIGH. Duplicate candidate flagged (80m away).',
        timestamp: new Date(Date.now() - 5 * 3600000 + 45000).toISOString(),
      },
      {
        id: 'hist-3',
        complaint_id: 'comp-4821',
        previous_status: 'VERIFIED',
        new_status: 'ASSIGNED',
        changed_by: 'P. Venkat Rao (EE Roads)',
        role: 'department_officer',
        note: 'Grievance assigned to Field Officer K. Suresh Kumar with 24-Hour SLA.',
        timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
      },
      {
        id: 'hist-4',
        complaint_id: 'comp-4821',
        previous_status: 'ASSIGNED',
        new_status: 'IN_PROGRESS',
        changed_by: 'K. Suresh Kumar (Field Officer)',
        role: 'field_officer',
        note: 'Field inspection completed. Repair crew deployed on site with asphalt batch.',
        timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
      },
    ],
    field_notes: [
      'Site visited at 11:30 AM. Pothole measured 1.4m x 0.9m x 14cm depth.',
      'School principal requested repair before afternoon dismissal.',
      'Cold mix batch delivered by municipal truck #TS-09-551.',
    ],
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004821',
  },
  {
    id: 'comp-4790',
    complaint_number: 'PV-2026-004790',
    citizen_id: 'user-citizen-2',
    citizen_name: 'Anil Babu',
    citizen_phone: '+91 98481 99001',
    title: 'Asphalt fragmentation on Main Road',
    description: 'Road surface peeling off near school bus stop.',
    original_language: 'en',
    category_id: 'roads',
    category_name: 'Road Infrastructure',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    latitude: 17.4406,
    longitude: 78.3493,
    address: '80m from ZP High School, Main Road, Gachibowli',
    ward: 'Ward 12',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-roads',
    department_name: 'Roads & Buildings Department',
    assigned_officer_id: 'user-officer-1',
    assigned_officer_name: 'K. Suresh Kumar',
    sla_hours_allotted: 24,
    sla_deadline: new Date(Date.now() + 18 * 3600000).toISOString(),
    sla_breached: false,
    evidence_quality_score: 79,
    evidence: [],
    history: [],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004790',
  },
  {
    id: 'comp-4612',
    complaint_number: 'PV-2026-004612',
    citizen_id: 'user-citizen-3',
    citizen_name: 'Sunita Rao',
    citizen_phone: '+91 94411 77665',
    title: 'Garbage accumulation near Colony School',
    description: 'Community dustbin overflowing for past 4 days. Waste spilled across pedestrian path.',
    original_language: 'en',
    category_id: 'sanitation',
    category_name: 'Sanitation & Solid Waste',
    priority: 'MEDIUM',
    status: 'SUBMITTED',
    latitude: 17.4382,
    longitude: 78.3512,
    address: 'Near Community Center, Ward 12, Gachibowli',
    ward: 'Ward 12',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-sanitation',
    department_name: 'Sanitation & Solid Waste Management',
    sla_hours_allotted: 48,
    sla_deadline: new Date(Date.now() + 32 * 3600000).toISOString(),
    sla_breached: false,
    evidence_quality_score: 82,
    evidence: [
      {
        id: 'evid-garb',
        complaint_id: 'comp-4612',
        uploaded_by: 'Sunita Rao',
        uploaded_by_role: 'citizen',
        file_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
        file_type: 'image',
        file_name: 'garbage_pile.jpg',
        file_size_kb: 380,
        evidence_stage: 'BEFORE',
        uploaded_at: new Date(Date.now() - 10 * 3600000).toISOString(),
      },
    ],
    history: [],
    created_at: new Date(Date.now() - 10 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 3600000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004612',
  },
  {
    id: 'comp-4519',
    complaint_number: 'PV-2026-004519',
    citizen_id: 'user-citizen-4',
    citizen_name: 'Mohammed Farooq',
    citizen_phone: '+91 97002 44332',
    title: 'Streetlight not working on Colony Lane 4',
    description: 'Two consecutive poles are completely dark since Friday storm. Safety hazard at night.',
    original_language: 'en',
    category_id: 'lighting',
    category_name: 'Public Lighting',
    priority: 'MEDIUM',
    status: 'CLOSED',
    latitude: 17.4429,
    longitude: 78.3451,
    address: 'Lane 4, Teachers Colony, Serilingampally',
    ward: 'Ward 13',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-lighting',
    department_name: 'Public Lighting & Electrical Wing',
    assigned_officer_id: 'user-officer-2',
    assigned_officer_name: 'V. Naresh (Lighting JE)',
    sla_hours_allotted: 24,
    sla_deadline: new Date(Date.now() - 24 * 3600000).toISOString(),
    sla_breached: false,
    evidence_quality_score: 90,
    evidence: [
      {
        id: 'evid-light-before',
        complaint_id: 'comp-4519',
        uploaded_by: 'Mohammed Farooq',
        uploaded_by_role: 'citizen',
        file_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
        file_type: 'image',
        file_name: 'dark_streetlight.jpg',
        file_size_kb: 310,
        evidence_stage: 'BEFORE',
        uploaded_at: new Date(Date.now() - 48 * 3600000).toISOString(),
      },
      {
        id: 'evid-light-after',
        complaint_id: 'comp-4519',
        uploaded_by: 'V. Naresh',
        uploaded_by_role: 'field_officer',
        file_url: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=800&q=80',
        file_type: 'image',
        file_name: 'replaced_led_luminaire.jpg',
        file_size_kb: 450,
        evidence_stage: 'AFTER',
        uploaded_at: new Date(Date.now() - 20 * 3600000).toISOString(),
      },
    ],
    history: [],
    citizen_feedback: {
      rating: 5,
      comment: 'Prompt resolution by the lighting technician. New LED light is very bright!',
      resolved: true,
      submitted_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    },
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004519',
  },
  {
    id: 'comp-4388',
    complaint_number: 'PV-2026-004388',
    citizen_id: 'user-citizen-5',
    citizen_name: 'G. Srinivas',
    citizen_phone: '+91 93910 88221',
    title: 'Blocked stormwater drainage canal',
    description: 'Canal choked with construction rubble and silt. Water backflowing into nearby residential basements.',
    original_language: 'en',
    category_id: 'drainage',
    category_name: 'Drainage & Stormwater',
    priority: 'HIGH',
    status: 'VERIFIED',
    latitude: 17.4365,
    longitude: 78.3475,
    address: 'Near Old Rythu Bazar, Gachibowli',
    ward: 'Ward 12',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-drainage',
    department_name: 'Drainage & Stormwater Department',
    sla_hours_allotted: 18,
    sla_deadline: new Date(Date.now() + 14 * 3600000).toISOString(),
    sla_breached: false,
    evidence_quality_score: 85,
    evidence: [],
    history: [],
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004388',
  },
  {
    id: 'comp-4102',
    complaint_number: 'PV-2026-004102',
    citizen_id: 'user-citizen-6',
    citizen_name: 'P. Aruna',
    citizen_phone: '+91 99881 22330',
    title: 'Drinking water pipeline rupture & leakage',
    description: 'Clean drinking water gushing onto the road under high pressure. Severe supply disruption.',
    original_language: 'te',
    translated_description: 'Clean drinking water gushing onto the road under high pressure. Severe supply disruption.',
    category_id: 'water',
    category_name: 'Water Supply',
    priority: 'CRITICAL',
    status: 'ASSIGNED',
    latitude: 17.4452,
    longitude: 78.3528,
    address: 'Plot 44, Telecom Nagar, Gachibowli',
    ward: 'Ward 12',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    department_id: 'dept-water',
    department_name: 'Municipal Water Supply & Sewerage Board',
    assigned_officer_id: 'user-officer-3',
    assigned_officer_name: 'B. Mahesh (HMWSSB AE)',
    sla_hours_allotted: 2,
    sla_deadline: new Date(Date.now() + 1 * 3600000 + 15 * 60000).toISOString(),
    sla_breached: false,
    evidence_quality_score: 88,
    evidence: [],
    history: [],
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
    qr_code_data: 'https://prajavaani.gov.in/track/PV-2026-004102',
  },
];

export const INITIAL_INCIDENT_CLUSTERS: IncidentCluster[] = [
  {
    id: 'cluster-1',
    title: 'Main Road Infrastructure & Pothole Hazard',
    category: 'Road Infrastructure',
    center_latitude: 17.4403,
    center_longitude: 78.3491,
    radius_meters: 180,
    complaint_count: 4,
    severity: 'HIGH',
    status: 'ACTIVE',
    affected_area: 'Ward 12, Zilla Parishad High School Road Corridor',
    complaint_numbers: ['PV-2026-004821', 'PV-2026-004790', 'PV-2026-004755', 'PV-2026-004710'],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'cluster-2',
    title: 'Drainage & Waterlogging Monsoon Risk',
    category: 'Drainage & Stormwater',
    center_latitude: 17.4370,
    center_longitude: 78.3480,
    radius_meters: 220,
    complaint_count: 3,
    severity: 'HIGH',
    status: 'INVESTIGATING',
    affected_area: 'Old Rythu Bazar Basements & Low-lying Lanes',
    complaint_numbers: ['PV-2026-004388', 'PV-2026-004350', 'PV-2026-004312'],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-citizen-1',
    complaint_id: 'comp-4821',
    complaint_number: 'PV-2026-004821',
    title: 'Officer Dispatched',
    message: 'Field Officer K. Suresh Kumar has arrived at the location and commenced road repair work.',
    type: 'STATUS_CHANGE',
    read: false,
    created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'user-officer-1',
    complaint_id: 'comp-4821',
    complaint_number: 'PV-2026-004821',
    title: 'New High Priority Assignment',
    message: 'PV-2026-004821: Dangerous Pothole Near School Entrance assigned with 24-hr SLA.',
    type: 'ASSIGNMENT',
    read: true,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'user-officer-1',
    complaint_id: 'comp-4102',
    complaint_number: 'PV-2026-004102',
    title: 'SLA Alert: Critical Emergency',
    message: 'Water pipeline rupture in Telecom Nagar requires immediate isolation valve shutdown (1h remaining).',
    type: 'SLA_WARNING',
    read: false,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    user_id: 'user-citizen-1',
    user_name: 'Ramesh Reddy',
    role: 'citizen',
    action: 'CREATE_COMPLAINT',
    entity_type: 'Complaint',
    entity_id: 'PV-2026-004821',
    new_value: 'Status: SUBMITTED | Category: Road Infrastructure',
    notes: 'Citizen submitted grievance via Mobile Voice Assistant in Telugu.',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'audit-2',
    user_id: 'system',
    user_name: 'AI Intelligence Engine',
    role: 'super_admin',
    action: 'AI_CLASSIFICATION',
    entity_type: 'Complaint',
    entity_id: 'PV-2026-004821',
    new_value: 'Priority: HIGH | Confidence: 91% | School Proximity Factor',
    notes: 'Explainable AI evaluated traffic safety, road surface depression, and school zone proximity.',
    timestamp: new Date(Date.now() - 5 * 3600000 + 45000).toISOString(),
  },
  {
    id: 'audit-3',
    user_id: 'user-dept-1',
    user_name: 'P. Venkat Rao',
    role: 'department_officer',
    action: 'ASSIGN_OFFICER',
    entity_type: 'Complaint',
    entity_id: 'PV-2026-004821',
    old_value: 'Unassigned',
    new_value: 'Officer: K. Suresh Kumar (Field Officer Roads)',
    notes: 'Official accepted AI routing recommendation to Roads & Buildings Department.',
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'audit-4',
    user_id: 'user-officer-1',
    user_name: 'K. Suresh Kumar',
    role: 'field_officer',
    action: 'UPLOAD_EVIDENCE',
    entity_type: 'ComplaintEvidence',
    entity_id: 'evid-2',
    new_value: 'Stage: PROGRESS | Asphalt batch leveling',
    notes: 'Field officer arrived on site and uploaded photographic progress proof.',
    timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
];
